name: Pipeline testen

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore TestCore/TestCore.csproj

      - name: Build
        run: dotnet build TestCore/TestCore.csproj -c Release --no-restore

      - name: Test
        run: dotnet test TestCore/TestCore.csproj -c Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory TestCore/TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestCore/TestResults
